```{r}
countries<-read.table(file="countries.txt",head=T,row.names=2,dec=",")
attach(countries)
le.fm.0 <- pmax(0,le.fm)
hist(le.fm.0,br=40)
```


```{r}

# Write your own CV bandwidth choice script for the local Poisson regression.
# h.cv.sm.possion.R
#
# method can be equal to 'loglik.CV' (default) or 'prob.missclas.CV'
h.cv.sm.poisson <- function(x,y,rg.h=NULL,l.h=10,method=prob.missclas.CV){
  cv.h <- numeric(l.h)
  if (is.null(rg.h)){
    hh <- c(h.select(x,y,method="cv"),h.select(x,y,method="aicc")) #,hcv(x,y))
    rg.h <- range(hh)
  }
  i <- 0
  gr.h <- exp( seq(log(rg.h[1]/1.1), log(rg.h[2]*1.1), l=l.h))
  for (h in gr.h){
    i <- i+1
    cv.h[i] <- method(x,y,h)
  }
  return(list(h=gr.h,cv.h=cv.h, h.cv = gr.h[which.min(cv.h)]))
}
# method 1
prob.missclas.CV <- function(x,y,h){
  n <- length(x)
  pred <- sapply(1:n, 
                 function(i,x,y,h){
                   sm.poisson(x=x[-i],y=y[-i],h=h,eval.points=x[i],display="none")$estimate
                 },   x,y,h)
  
  return(sum(abs(pred-y)>.5)/n)
}
# method 2
loglik.CV <- function(x,y,h){
  n <- length(x)
  lambda <- sapply(1:n, 
                 function(i,x,y,h){
                   sm.poisson(x=x[-i],y=y[-i],h=h,eval.points=x[i],display="none")$estimate
                 },   x,y,h)
  
  return (-sum(log(exp(-lambda)*(lambda^x)/(factorial(x)))))# using minus here is aim to keep using min later
}
```



```{r}
h.list.ps <- h.cv.sm.poisson(inf.mort,le.fm.0)#rg.h=c(4,11)
h.list.ll <- h.cv.sm.poisson(inf.mort,le.fm.0,method = loglik.CV)
```

Using method 1 prob.missclas.CV:
```{r}
aux <- sm.poisson(inf.mort,le.fm.0,h=h.list.ps$h.cv, col=1)
sm.regression(inf.mort,le.fm.0,h=h.list.ps$h.cv,col=4,add=T)
aux.glm <- glm(le.fm.0 ~ inf.mort,family=poisson)
pred <- predict(aux.glm, 
                newdata=data.frame(inf.mort=aux$eval.points),
                type="response")
lines(aux$eval.points,pred,col=2)
```
Using method 2 loglik.CV:
```{r}
aux <- sm.poisson(inf.mort,le.fm.0,h=h.list.ll$h.cv, col=1)
sm.regression(inf.mort,le.fm.0,h=h.list.ll$h.cv,col=4,add=T)
aux.glm <- glm(le.fm.0 ~ inf.mort,family=poisson)
pred <- predict(aux.glm, 
                newdata=data.frame(inf.mort=aux$eval.points),
                type="response")
lines(aux$eval.points,pred,col=2)
```

The h valuse are similar: `h.list.ll$h.cv`,`h.list.ps$h.cv`